name: ODataRequest_build_test

on:
  push:
    branches-ignore:
      - main
    paths:
      - "Frends.Sap.ODataRequest/**"
  workflow_dispatch:

jobs:
  build:
    uses: FrendsPlatform/FrendsTasks/.github/workflows/linux_build_test.yml@main
    with:
      workdir: Frends.Sap.ODataRequest
      env_var_name_1: USERNAME
      env_var_name_2: PASSWORD
      env_var_name_3: HOST
      env_var_name_4: PORT
    secrets:
      badge_service_api_key: ${{ secrets.BADGE_SERVICE_API_KEY }}
      test_feed_api_key: ${{ secrets.TASKS_TEST_FEED_API_KEY }}
      env_var_value_1: ${{ secrets.USERNAME }}
      env_var_value_2: ${{ secrets.PASSWORD }}
      env_var_value_3: ${{ secrets.HOST }}
      env_var_value_4: ${{ secrets.PORT }}
